export const darkColorScheme = {
  // Root palette
  primaryMain: '#6ae8fa',
  primaryPressed: '#2abdd2',
  secondaryMain: '#A9B7C1',
  infoMain: '#006DD1',
  infoSecondary: '#29B8F566',

  // NPS Card accents
  accentLight: '#f7d9ff',
  accentMid: '#d5e3fe',
  accentDark: '#93b2ff',

  // Button states
  accentDefault: '#c428dd',
  accentHover: '#c428ddd9',
  accentPressed: '#c428ddb3',
  accentDisabled: '#c428dd66',
  outlineDefault: '#3d44561a',
  outlineHover: '#3d455726',
  outlinePressed: '#3d445633',

  // Text
  textPrimary: '#A9B7C1',
  textEmphasis: '#FFFFFF',
  textDisabled: '#686C76',
  textOnAccent: '#FFFFFF',
  textOnButton: '#0E131D',
  textOnTooltip: '#0E131D',
  textPlaceholder: '#3B3E46',
  textInputDisabled: '#ffffff80',
  textMuted: '#777A83',
  textInverse: '#0E131D',
  textMetrics: '#CAD0D8',
  textCreateButton: '#6ae8fa',
  textShowMore: '#2abdd2',
  textAuxiliaryHover: '#83EFFF',

  // Text: statuses
  textError: '#D71616',
  textErrorSubtle: '#ffdfdf',
  textSuccessSubtle: '#dcffe9',
  textWarningSubtle: '#ffebd3',
  textAttention: '#ffebd3',
  textInfo: '#29B8F5',
  textInfoSubtle: '#d7f1ff',
  textTips: '#C7EBFF',

  // Text: links
  textLink: '#29B8F5',
  textLinkVisited: '#29b8f5b3',

  // Icons
  iconDefault: '#A9B7C1',
  iconEmphasis: '#FFFFFF',
  iconPrimary: '#ABB3B9',
  iconOnAccent: '#FFFFFF',
  iconSend: '#0E131D',
  iconDisabled: '#686C76',
  iconHover: '#CAD0D8',
  iconDelete: '#181F2A',
  iconActive: '#2abdd2',
  iconInactive: '#29b8f5',
  iconInfo: '#29B8F5',
  iconTips: '#29B8F5',
  iconSuccess: '#2BD48D',
  iconSuccessStrong: '#15A42A',
  iconSuccessSubtle: '#2bd48d33',
  iconWarning: '#E97912',
  iconAttention: '#F2994A',
  iconError: '#D71616',
  iconTrophy: '#FFD3A0',
  iconMagicAssistant: '#f47cff',
  iconResultInfo: '#29b8f5',

  // Borders
  borderDefault: '#3B3E46',
  borderHover: '#A9B7C1',
  borderInputHover: '#686C76',
  borderSelected: '#ffffff33',
  borderInfo: '#29b8f566',
  borderSurface: '#262b34',
  borderSurfaceStrong: '#0E131D',
  borderDivider: '#ffffff1a',
  borderEditor: '#2abdd2',
  borderHighlight: '#de7eda66',
  borderChatInput: '#006DD1',
  borderMcpSuccess: '#2bd48d66',
  borderSuccess: '#2ab37a66',
  borderWarning: '#e9791266',
  borderError: '#d7161666',
  borderMcpLogout: '#e8791166',
  borderChatContinue: '#6ae8fa4d',
  borderReindex: '#F1BD17',
  borderResultInfo: '#29b8f566',
  borderAccent: '#93b2ff',
  borderCardOutlineStart: '#262B34',
  borderCardOutlineEnd: '#313A48',
  borderToolCardStart: '#ffffff12',
  borderToolCardEnd: '#ffffff00',
  borderAiProviderStart: '#ffffff12',
  borderAiProviderEnd: '#ffffff00',

  // Shadows
  shadowDefault: '#ffffff24',
  shadowTagEditorPaper: '#0000004d',
  shadowTag: '#00000000',
  shadowOnboarding: '#29b8f533',
  shadowAiAnswer: '#00000000',

  // Selection controls
  selectionControlDefault: '#A9B7C1',
  selectionControlEmphasis: '#FFFFFF',
  selectionControlMark: '#0E131D',
  selectionControlDisabled: '#686C76',

  // Split control
  splitBackgroundDefault: '#6ae8fa33',
  splitBackgroundHover: '#6ae8fa4d',
  splitBackgroundPressed: '#6ae8fa1a',
  splitBackgroundDisabled: '#ffffff1a',
  splitTextDefault: '#6ae8fa',
  splitTextPressed: '#2abdd2',
  splitTextDisabled: '#A9B7C1',

  // Scrollbar
  scrollbarThumb: '#ffffff1a',
  scrollbarThumbHover: '#A9B7C1',

  // Suggestion chip
  suggestionChipBorder: '#3B3E46',
  suggestionChipBackgroundDefault: '#00000000',
  suggestionChipBackgroundHover: '#ffffff1a',
  suggestionChipTextDefault: '#CAD0D8',
  suggestionChipTextHover: '#FFFFFF',

  // Steps
  stepDefaultBorder: '#757575',
  stepDefaultIcon: '#ffffff1a',
  stepActive: '#006dd166',
  stepCompletedBorder: '#006dd166',
  stepCompletedBackground: '#036ED033',
  stepCompletedIcon: '#006DD1',

  // Statuses
  statusDraft: '#29B8F5',
  statusModeration: '#E97912',
  statusWarningText: '#FFEBD3',
  statusPublished: '#2BD48D',
  statusPublishedIcon: '#108D22',
  statusPublishedBackground: '#2BD48D',
  statusPublishedText: '#FFFFFF',
  statusPublishedBorder: '#2AB37A',
  statusRejected: '#D71616',
  statusRejectedText: '#ffdfdf',
  statusUserApproval: '#f47cff',

  // Warnings
  warningMain: '#ED6C02',
  warningYellow: '#E8B747',
  warningSurface: '#fff3e0',
  warningTextStrong: '#e65100',

  // Diff
  diffRemoved: '#d716164d',
  diffAdded: '#2ab37a4d',

  // Capabilities
  capabilityVisionBackground: '#2A2F46',
  capabilityVisionIcon: '#7C69B4',
  capabilityReasoningBackground: '#362F2E',
  capabilityReasoningIcon: '#A5695C',

  // AI assistant
  aiAssistantBackgroundStart: '#29a9a561',
  aiAssistantBackgroundEnd: '#e72feb61',
  aiAssistantBorderStart: '#29fff8a3',
  aiAssistantBorderEnd: '#fb48ff18',
  aiAssistantIconStart: '#50D2CE',
  aiAssistantIconEnd: '#FA00FF',

  // Backgrounds: base surfaces
  backgroundInfo: '#6ae8fa14',
  backgroundPage: '#0E131D',
  backgroundSecondary: '#181F2A',
  backgroundTabPanel: '#101721',
  backgroundPageSection: '#0E131D',
  backgroundSection: '#ffffff08',
  backgroundModal: '#181F2A',
  backgroundChat: '#101721',
  backgroundDragging: '#6ae8fa1a',
  backgroundUserInput: '#ffffff0d',
  backgroundUserInputActive: '#ffffff1a',
  backgroundUserInputBorderLight: '#1ed1de',
  backgroundUserInputBorderDark: '#0f5160',
  backgroundUserInputBorderShadow: '#15fff733',
  backgroundDangerMuted: '#d7161626',
  backgroundDangerStrong: '#d7161666',
  backgroundDangerSubtle: '#d7161614',
  backgroundOnboarding: '#0c1119',
  backgroundWarning: '#e97912',
  backgroundWarningStrong: '#e9791266',
  backgroundWarningSubtle: '#e9791214',
  backgroundCodeEditor: '#101721',
  backgroundDragHighlight: '#3d3d3d',

  // Backgrounds: controls
  backgroundCategorySelected: '#006DD1',
  backgroundCategorySelectedHover: '#29B8F566',
  backgroundDataGrid: '#262b34',
  backgroundDataGridSecondary: '#101721',
  backgroundDataGridRowSelected: '#6ae8fa29',
  backgroundTabButtonDefault: '#ffffff0d',
  backgroundTabButtonHover: '#ffffff1a',
  backgroundTabButtonActive: '#ffffff33',
  backgroundTabButtonDisabled: '#ffffff0d',
  backgroundSelectHover: '#ffffff1a',
  backgroundSelectSelected: '#6ae8fa29',
  backgroundSelectSelectedHover: '#6ae8fa3d',
  switchThumbOn: '#6ae8fa',
  switchTrackOn: '#6ae8fa4d',
  switchThumbOff: '#A9B7C1',
  switchTrackOff: '#ffffff33',
  switchThumbOnDisabled: '#267985',
  switchTrackOnDisabled: '#6ae8fa4d',
  switchThumbOffDisabled: '#686C76',
  switchTrackOffDisabled: '#ffffff33',
  backgroundTabsActive: '#6ae8fa',
  backgroundTabDefault: '#A9B7C1',
  backgroundTabHover: '#2abdd2',
  backgroundTabActive: '#6ae8fa',
  backgroundTabDisabled: '#686C76',
  backgroundTooltip: '#CAD0D8',
  backgroundTooltipCode: '#3d445633',

  // Backgrounds: cards
  backgroundCard: '#181F2A',
  backgroundCardHover: '#0c1119',
  backgroundCardGradientStart: '#121820',
  backgroundCardGradientEnd: '#1D232C',
  backgroundCardHoverBorderStart: '#53b0bf66',
  backgroundCardHoverBorderEnd: '#53B0BF',
  backgroundCardHoverShadow: '#78e6ff4d',

  // Backgrounds: interactive tour
  backgroundTourBackdrop: '#3b3e4680',
  backgroundTourCardStart: '#122543',
  backgroundTourCardEnd: '#194386',
  backgroundTourBorderStart: '#2773EE',
  backgroundTourBorderEnd: '#1A3C74',
  backgroundTourDividerEdge: '#2670e800',
  backgroundTourDividerCenter: '#26ABE8',
  backgroundTourCounter: '#5c82bf',

  // Backgrounds: resource cards
  backgroundResourceBlueStart: '#0e273e66',
  backgroundResourceBlueEnd: '#0E273E',
  backgroundResourceOrangeStart: '#3b332866',
  backgroundResourceOrangeEnd: '#3B3328',
  backgroundResourcePurpleStart: '#291d4066',
  backgroundResourcePurpleEnd: '#291D40',
  backgroundResourceGreenStart: '#142f2366',
  backgroundResourceGreenEnd: '#142F23',
  backgroundResourcePinkStart: '#3A1B27',
  backgroundResourcePinkEnd: '#3a1b2766',

  // Backgrounds: icons
  backgroundIconDefault: '#ffffff1a',
  backgroundIconTrophy: '#48433F',
  backgroundIconChecked: '#A9B7C1',
  backgroundIconEntityStart: '#a9b7c14d',
  backgroundIconEntityEnd: '#a9b7c117',
  backgroundIconEntityBorderStart: '#9ca9b200',
  backgroundIconEntityBorderEnd: '#9ca9b266',

  // Backgrounds: buttons
  backgroundButtonDefault: '#ffffff1a',
  backgroundButtonDanger: '#D71616',
  backgroundButtonPrimaryDefault: '#6ae8fa',
  backgroundButtonPrimaryHover: '#83EFFF',
  backgroundButtonPrimaryPressed: '#2abdd2',
  backgroundButtonPrimaryDisabled: '#686C76',
  backgroundButtonSecondaryDefault: '#ffffff1a',
  backgroundButtonSecondaryHover: '#ffffff33',
  backgroundButtonSecondaryPressed: '#0E131D',
  backgroundButtonSecondaryDisabled: '#686C76',
  backgroundButtonTertiaryHover: '#ffffff1a',
  backgroundButtonTertiaryPressed: '#ffffff33',
  backgroundButtonAlarmDefault: '#D71616',
  backgroundButtonAlarmHover: '#E74444',
  backgroundButtonAlarmPressed: '#C51111',
  backgroundButtonAlarmDisabled: '#686C76',
  backgroundButtonTransparent: '#00000000',
  backgroundButtonDrawerHover: '#ffffff0d',
  backgroundButtonDrawerSelected: '#ffffff1a',
  backgroundButtonAgentHubHover: '#60339F33',
  backgroundButtonAgentHubActive: '#60339F33',
  backgroundButtonAgentHubShadow: '#66D1FF1A',
  backgroundButtonAgentHubTextStart: '#58CDEA',
  backgroundButtonAgentHubTextEnd: '#AF64FF',
  backgroundButtonAgentHubIconStart: '#58CDEA',
  backgroundButtonAgentHubIconEnd: '#AF64FF',
  backgroundButtonIconLabelHover: '#ffffff0d',
  backgroundButtonIconLabelSelected: '#ffffff1a',
  backgroundButtonNeutralDefault: '#006DD1',
  backgroundButtonNeutralHover: '#2783D8',
  backgroundButtonNeutralPressed: '#006DD1',
  backgroundButtonNeutralDisabled: '#686C76',
  backgroundButtonPositiveDefault: '#108D22',
  backgroundButtonPositiveHover: '#15A42A',
  backgroundButtonPositivePressed: '#108D22',
  backgroundButtonPositiveDisabled: '#686C76',
  backgroundButtonMagicAssistant: '#f47cff3d',

  // Backgrounds: conversations
  backgroundTips: '#29b8f50d',
  backgroundAttention: '#e979120d',
  backgroundTextHighlight: '#F2994A',
  backgroundAiAnswer: '#262b34',
  backgroundAiParticipantIcon: '#29b8f533',
  backgroundAiAnswerActionsStart: '#262B34',
  backgroundAiAnswerActionsEnd: '#262b3400',
  backgroundUserMessageActionsStart: '#0E131D',
  backgroundUserMessageActionsEnd: '#0e131d00',
  backgroundConversationStarter: '#de7eda33',
  backgroundConversationStarterHover: '#de7eda66',
  backgroundConversationEditor: '#262b34',
  backgroundConversationCoverTransparent: '#10172100',
  backgroundConversationCoverOpaque: '#0E131D',
  backgroundAvatar: '#1a1f28',
  backgroundCategoryHeader: '#0E131D',
  backgroundTag: '#181F2A',
  backgroundTagSelected: '#006DD1',
  backgroundNotificationList: '#262b34',
  backgroundParticipant: '#ffffff0d',
  backgroundParticipantHover: '#ffffff1a',
  backgroundParticipantActive: '#6ae8fa1a',
  backgroundParticipantCover: '#10172180',
  backgroundConversationNormal: '#00000000',
  backgroundConversationHover: '#ffffff0f',
  backgroundConversationSelected: '#29b8f526',
  backgroundHighlightUserMessage: '#de7eda33',
  backgroundTagEditor: '#262b34',
  backgroundTagChip: '#181F2A',
  backgroundTagChipHover: '#ffffff33',
  backgroundTagChipActive: '#f551f94d',
  backgroundTagChipActiveHover: '#f551f933',
  backgroundTagChipDisabled: '#ffffff1a',

  // Backgrounds: application surfaces
  backgroundEliteaStart: '#0E131D',
  backgroundEliteaEnd: '#0E131D',
  backgroundContextDialogStart: '#181F2A',
  backgroundContextDialogEnd: '#181F2A',
  backgroundSidebarStart: '#0F1E33',
  backgroundSidebarEnd: '#1B172C',

  // Backgrounds: modals and attachments
  backgroundImageAttachmentStart: '#262B34',
  backgroundImageAttachmentEnd: '#3b3e4600',
  backgroundAgentModalBorderStart: '#256B6D',
  backgroundAgentModalBorderEnd: '#7E2988',
  backgroundAgentModalStart: '#122830',
  backgroundAgentModalEnd: '#2C173A',
  backgroundAgentModalContent: '#0E131D',
  backgroundToolCardHover: '#ffffff14',
  backgroundDeprecated: '#d37015',
  backgroundMcpSuccess: '#2bd48e14',
  backgroundMcpLogout: '#e9791214',

  // Backgrounds: onboarding and banners
  backgroundOnboardingStart: '#a1c5ff99',
  backgroundOnboardingMiddle: '#a1c5ff1f',
  backgroundOnboardingEnd: '#a1d6ff99',
  backgroundWelcomeOutsideStart: '#61ede966',
  backgroundWelcomeOutsideEnd: '#fb42ff66',
  backgroundWelcomeInnerStart: '#29a9a524',
  backgroundWelcomeInnerEnd: '#e72feb24',
  backgroundBannerStart: '#3d2519',
  backgroundBannerEnd: '#240f3c',
  backgroundBannerBorderStart: '#a05714',
  backgroundBannerBorderEnd: '#7513aa',

  // Backgrounds: feature surfaces
  backgroundChatContinue: '#ffffff1a',
  backgroundAiProvider: '#ffffff05',
  backgroundAiProviderHover: '#ffffff0d',
  backgroundEmptyState: '#ffffff08',
  backgroundToolkitPanel: '#151C25',
  backgroundIndexSuccess: '#2bd48e14',
  backgroundIndexError: '#d7161614',
  backgroundIndexWarning: '#e9791214',
  backgroundIndexInfo: '#29b8f514',

  // Backgrounds: folders
  backgroundFolder: '#ffffff05',
  backgroundFolderActive: '#f551f91a',
  backgroundFolderBorderStart: '#ffffff12',
  backgroundFolderBorderEnd: '#ffffff00',
  backgroundFolderBorderHover: '#f551f94d',
  backgroundFolderBorderActive: '#f551f94d',
  backgroundFolderShadow: '#00000000',
};
