export const lightColorScheme = {
  // Root palette
  primaryMain: '#c428dd',
  primaryPressed: '#c428dd',
  secondaryMain: '#777A83',
  infoMain: '#6390fe',
  infoSecondary: '#6eb1ff',

  // NPS Card accents
  accentLight: '#f7d9ff',
  accentMid: '#d5e3fe',
  accentDark: '#93b2ff',

  // Button states
  accentDefault: '#c428dd',
  accentHover: '#c428ddd9',
  accentPressed: '#c428ddb3',
  accentDisabled: '#c428dd66',
  outlineDefault: '#3d44561a',
  outlineHover: '#3d445626',
  outlinePressed: '#3d445633',

  // Text
  textPrimary: '#777A83',
  textEmphasis: '#0E131D',
  textDisabled: '#adafb7',
  textOnAccent: '#FFFFFF',
  textOnButton: '#f8fcff',
  textOnTooltip: '#FFFFFF',
  textPlaceholder: '#cbced6',
  textInputDisabled: '#777A83',
  textMuted: '#777A83',
  textInverse: '#0E131D',
  textMetrics: '#5B5E69',
  textCreateButton: '#0E131D',
  textShowMore: '#c428dd',
  textAuxiliaryHover: '#f47cff',

  // Text: statuses
  textError: '#D71616',
  textErrorSubtle: '#d71616',
  textSuccessSubtle: '#2AB37A',
  textWarningSubtle: '#F2994A',
  textAttention: '#D37015',
  textInfo: '#6390fe',
  textInfoSubtle: '#006DD1',
  textTips: '#006DD1',

  // Text: links
  textLink: '#006DD1',
  textLinkVisited: '#006dd1b3',

  // Icons
  iconDefault: '#777A83',
  iconEmphasis: '#0E131D',
  iconPrimary: '#ABB3B9',
  iconOnAccent: '#FFFFFF',
  iconSend: '#FFFFFF',
  iconDisabled: '#adafb7',
  iconHover: '#5B5E69',
  iconDelete: '#FFFFFF',
  iconActive: '#c428dd',
  iconInactive: '#29B8F5',
  iconInfo: '#29B8F5',
  iconTips: '#006DD1',
  iconSuccess: '#2AB37A',
  iconSuccessStrong: '#15A42A',
  iconSuccessSubtle: '#2bd48d33',
  iconWarning: '#E97912',
  iconAttention: '#F2994A',
  iconError: '#D71616',
  iconTrophy: '#FFD3A0',
  iconMagicAssistant: '#f47cff',
  iconResultInfo: '#006DD1',

  // Borders
  borderDefault: '#cbced6',
  borderHover: '#777A83',
  borderInputHover: '#adafb7',
  borderSelected: '#3d445633',
  borderInfo: '#6eb1ff',
  borderSurface: '#e1e5e9',
  borderSurfaceStrong: '#e1e5e9',
  borderDivider: '#3d44561a',
  borderEditor: '#c428dd',
  borderHighlight: '#50a1ff66',
  borderChatInput: '#6390fe',
  borderMcpSuccess: '#2bd48d66',
  borderSuccess: '#2ab37a66',
  borderWarning: '#e9791266',
  borderError: '#d7161666',
  borderMcpLogout: '#e9791266',
  borderChatContinue: '#f551f94d',
  borderReindex: '#FEBD17',
  borderResultInfo: '#50a1ff66',
  borderAccent: '#93b2ff',
  borderCardOutlineStart: '#d0d5da99',
  borderCardOutlineEnd: '#D0D5DA',
  borderToolCardStart: '#e1e5e9',
  borderToolCardEnd: '#e1e5e9',
  borderAiProviderStart: '#41475714',
  borderAiProviderEnd: '#41475700',

  // Shadows
  shadowDefault: '#64778833',
  shadowTagEditorPaper: '#64778833',
  shadowTag: '#0000000f',
  shadowOnboarding: '#50a1ff33',
  shadowAiAnswer: '#0000001f',

  // Selection controls
  selectionControlDefault: '#777A83',
  selectionControlEmphasis: '#0E131D',
  selectionControlMark: '#FFFFFF',
  selectionControlDisabled: '#adafb7',

  // Split control
  splitBackgroundDefault: '#f551f933',
  splitBackgroundHover: '#f551f94d',
  splitBackgroundPressed: '#f551f91a',
  splitBackgroundDisabled: '#3d44561a',
  splitTextDefault: '#0E131D',
  splitTextPressed: '#0E131D',
  splitTextDisabled: '#777A83',

  // Scrollbar
  scrollbarThumb: '#3d44561a',
  scrollbarThumbHover: '#777A83',

  // Suggestion chip
  suggestionChipBorder: '#cbced6',
  suggestionChipBackgroundDefault: '#00000000',
  suggestionChipBackgroundHover: '#3d44561a',
  suggestionChipTextDefault: '#5B5E69',
  suggestionChipTextHover: '#0E131D',

  // Steps
  stepDefaultBorder: '#bdbdbd',
  stepDefaultIcon: '#3d44561a',
  stepActive: '#006dd166',
  stepCompletedBorder: '#006DD1',
  stepCompletedBackground: '#036ED033',
  stepCompletedIcon: '#006DD1',

  // Statuses
  statusDraft: '#6390fe',
  statusModeration: '#E97912',
  statusWarningText: '#D37015',
  statusPublished: '#2AB37A',
  statusPublishedIcon: '#108D22',
  statusPublishedBackground: '#2bd48d14',
  statusPublishedText: '#15A42A',
  statusPublishedBorder: '#2AB37A',
  statusRejected: '#D71616',
  statusRejectedText: '#D71616',
  statusUserApproval: '#f47cff',

  // Warnings
  warningMain: '#ED6C02',
  warningYellow: '#FFC124',
  warningSurface: '#fff3e0',
  warningTextStrong: '#e65100',

  // Diff
  diffRemoved: '#d716164d',
  diffAdded: '#2ab37a4d',

  // Capabilities
  capabilityVisionBackground: '#F0EDF7',
  capabilityVisionIcon: '#A48EE3',
  capabilityReasoningBackground: '#FFF1E4',
  capabilityReasoningIcon: '#FFB380',

  // AI assistant
  aiAssistantBackgroundStart: '#68b1ff61',
  aiAssistantBackgroundEnd: '#fda1ff61',
  aiAssistantBorderStart: '#299bff21',
  aiAssistantBorderEnd: '#fb37ffa3',
  aiAssistantIconStart: '#F534FF',
  aiAssistantIconEnd: '#5CA0FE',

  // Backgrounds: base surfaces
  backgroundInfo: '#6ae8fa14',
  backgroundPage: '#f8fcff',
  backgroundSecondary: '#FFFFFF',
  backgroundTabPanel: '#fafafa',
  backgroundPageSection: '#fafafa',
  backgroundSection: '#41475708',
  backgroundModal: '#FFFFFF',
  backgroundChat: '#FAFAFA',
  backgroundDragging: '#6390fe1f',
  backgroundUserInput: '#3d44560d',
  backgroundUserInputActive: '#3d44561a',
  backgroundUserInputBorderLight: '#f551f9',
  backgroundUserInputBorderDark: '#feb4ff',
  backgroundUserInputBorderShadow: '#f12bff33',
  backgroundDangerMuted: '#d7161626',
  backgroundDangerStrong: '#d7161666',
  backgroundDangerSubtle: '#d7161614',
  backgroundOnboarding: '#fafafa',
  backgroundWarning: '#E97912',
  backgroundWarningStrong: '#e9791266',
  backgroundWarningSubtle: '#e9791214',
  backgroundCodeEditor: '#FAFAFA',
  backgroundDragHighlight: '#3d3d3d',

  // Backgrounds: controls
  backgroundCategorySelected: '#6390fe',
  backgroundCategorySelectedHover: '#6eb1ff',
  backgroundDataGrid: '#e1e5e9',
  backgroundDataGridSecondary: '#fafafa',
  backgroundDataGridRowSelected: '#c428dd14',
  backgroundTabButtonDefault: '#3d44560d',
  backgroundTabButtonHover: '#3d44561a',
  backgroundTabButtonActive: '#3d445633',
  backgroundTabButtonDisabled: '#3d44560d',
  backgroundSelectHover: '#3d44561a',
  backgroundSelectSelected: '#f551f929',
  backgroundSelectSelectedHover: '#f551f93d',
  switchThumbOn: '#c428dd',
  switchTrackOn: '#f551f94d',
  switchThumbOff: '#777A83',
  switchTrackOff: '#3d445633',
  switchThumbOnDisabled: '#CB93D4',
  switchTrackOnDisabled: '#f551f94d',
  switchThumbOffDisabled: '#adafb7',
  switchTrackOffDisabled: '#3d445633',
  backgroundTabsActive: '#c428dd',
  backgroundTabDefault: '#777A83',
  backgroundTabHover: '#f47cff',
  backgroundTabActive: '#c428dd',
  backgroundTabDisabled: '#adafb7',
  backgroundTooltip: '#3B3E46',
  backgroundTooltipCode: '#ffffff26',

  // Backgrounds: cards
  backgroundCard: '#FFFFFF',
  backgroundCardHover: '#FFFFFF',
  backgroundCardGradientStart: '#FFFFFF',
  backgroundCardGradientEnd: '#ffffff00',
  backgroundCardHoverBorderStart: '#f7aeff',
  backgroundCardHoverBorderEnd: '#F37DFF',
  backgroundCardHoverShadow: '#e138ff4d',

  // Backgrounds: interactive tour
  backgroundTourBackdrop: '#3b3e4680',
  backgroundTourCardStart: '#EFF8FF',
  backgroundTourCardEnd: '#BAD1FF',
  backgroundTourBorderStart: '#5194FF',
  backgroundTourBorderEnd: '#A6DAFF',
  backgroundTourDividerEdge: '#f68eff00',
  backgroundTourDividerCenter: '#8DACFF',
  backgroundTourCounter: '#5c82bf',

  // Backgrounds: resource cards
  backgroundResourceBlueStart: '#d6ebff66',
  backgroundResourceBlueEnd: '#D6EBFF',
  backgroundResourceOrangeStart: '#ffcf8d4d',
  backgroundResourceOrangeEnd: '#ffcf8d1f',
  backgroundResourcePurpleStart: '#F0E7FF',
  backgroundResourcePurpleEnd: '#f0e7ff66',
  backgroundResourceGreenStart: '#d3fbdb66',
  backgroundResourceGreenEnd: '#d3fbdb',
  backgroundResourcePinkStart: '#FFE8F1',
  backgroundResourcePinkEnd: '#ffe8f166',

  // Backgrounds: icons
  backgroundIconDefault: '#3d44561a',
  backgroundIconTrophy: '#48433F',
  backgroundIconChecked: '#777A83',
  backgroundIconEntityStart: '#777a7c4d',
  backgroundIconEntityEnd: '#e2e2e24d',
  backgroundIconEntityBorderStart: '#3b42461a',
  backgroundIconEntityBorderEnd: '#3b424659',

  // Backgrounds: buttons
  backgroundButtonDefault: '#3d44561a',
  backgroundButtonDanger: '#D71616',
  backgroundButtonPrimaryDefault: '#c428dd',
  backgroundButtonPrimaryHover: '#f47cff',
  backgroundButtonPrimaryPressed: '#f47cff',
  backgroundButtonPrimaryDisabled: '#adafb7',
  backgroundButtonSecondaryDefault: '#3d44561a',
  backgroundButtonSecondaryHover: '#3d445633',
  backgroundButtonSecondaryPressed: '#3d445633',
  backgroundButtonSecondaryDisabled: '#adafb7',
  backgroundButtonTertiaryHover: '#3d44561a',
  backgroundButtonTertiaryPressed: '#3d44561a',
  backgroundButtonAlarmDefault: '#D71616',
  backgroundButtonAlarmHover: '#E74444',
  backgroundButtonAlarmPressed: '#C51111',
  backgroundButtonAlarmDisabled: '#adafb7',
  backgroundButtonTransparent: '#00000000',
  backgroundButtonDrawerHover: '#3d44560d',
  backgroundButtonDrawerSelected: '#3d44561a',
  backgroundButtonAgentHubHover: '#C6B8FF33',
  backgroundButtonAgentHubActive: '#C6B8FF33',
  backgroundButtonAgentHubShadow: '#A754FF33',
  backgroundButtonAgentHubTextStart: '#DD32FF',
  backgroundButtonAgentHubTextEnd: '#8147FF',
  backgroundButtonAgentHubIconStart: '#E345FF',
  backgroundButtonAgentHubIconEnd: '#A274FF',
  backgroundButtonIconLabelHover: '#3d44560d',
  backgroundButtonIconLabelSelected: '#3d44561a',
  backgroundButtonNeutralDefault: '#006DD1',
  backgroundButtonNeutralHover: '#2783D8',
  backgroundButtonNeutralPressed: '#006DD1',
  backgroundButtonNeutralDisabled: '#adafb7',
  backgroundButtonPositiveDefault: '#108D22',
  backgroundButtonPositiveHover: '#15A42A',
  backgroundButtonPositivePressed: '#108D22',
  backgroundButtonPositiveDisabled: '#adafb7',
  backgroundButtonMagicAssistant: '#f47cff3d',

  // Backgrounds: conversations
  backgroundTips: '#29b8f514',
  backgroundAttention: '#e979120d',
  backgroundTextHighlight: '#F2994A',
  backgroundAiAnswer: '#FFFFFF',
  backgroundAiParticipantIcon: '#50a1ff33',
  backgroundAiAnswerActionsStart: '#FFFFFF',
  backgroundAiAnswerActionsEnd: '#ffffff00',
  backgroundUserMessageActionsStart: '#EFF3FA',
  backgroundUserMessageActionsEnd: '#ecf1f900',
  backgroundConversationStarter: '#50a1ff33',
  backgroundConversationStarterHover: '#50a1ff66',
  backgroundConversationEditor: '#e1e5e9',
  backgroundConversationCoverTransparent: '#ffffff00',
  backgroundConversationCoverOpaque: '#FFFFFF',
  backgroundAvatar: '#d9d9d9',
  backgroundCategoryHeader: '#f8fcff',
  backgroundTag: '#FFFFFF',
  backgroundTagSelected: '#6390fe',
  backgroundNotificationList: '#FFFFFF',
  backgroundParticipant: '#3d44560d',
  backgroundParticipantHover: '#3d44561a',
  backgroundParticipantActive: '#f551f91a',
  backgroundParticipantCover: '#ffffff80',
  backgroundConversationNormal: '#00000000',
  backgroundConversationHover: '#3d44560f',
  backgroundConversationSelected: '#6390fe1f',
  backgroundHighlightUserMessage: '#50a1ff33',
  backgroundTagEditor: '#e1e5e9',
  backgroundTagChip: '#fafafa',
  backgroundTagChipHover: '#3d445633',
  backgroundTagChipActive: '#6390fe',
  backgroundTagChipActiveHover: '#6eb1ff',
  backgroundTagChipDisabled: '#3d44561a',

  // Backgrounds: application surfaces
  backgroundEliteaStart: '#EBF1F8',
  backgroundEliteaEnd: '#FFF9FF',
  backgroundContextDialogStart: '#EBF1F8',
  backgroundContextDialogEnd: '#FFF9FF',
  backgroundSidebarStart: '#E4F0FF',
  backgroundSidebarEnd: '#FDEAFF',

  // Backgrounds: modals and attachments
  backgroundImageAttachmentStart: '#FFFFFF',
  backgroundImageAttachmentEnd: '#ffffff00',
  backgroundAgentModalBorderStart: '#8BC9FF',
  backgroundAgentModalBorderEnd: '#FDA3FF',
  backgroundAgentModalStart: '#DEEDFF',
  backgroundAgentModalEnd: '#F9DFFE',
  backgroundAgentModalContent: '#f8fcff',
  backgroundToolCardHover: '#3d445614',
  backgroundDeprecated: '#D37015',
  backgroundMcpSuccess: '#2bd48d14',
  backgroundMcpLogout: '#e9791214',

  // Backgrounds: onboarding and banners
  backgroundOnboardingStart: '#a1c5ff99',
  backgroundOnboardingMiddle: '#a1c5ff1f',
  backgroundOnboardingEnd: '#a1d6ff99',
  backgroundWelcomeOutsideStart: '#61ede966',
  backgroundWelcomeOutsideEnd: '#fb42ff66',
  backgroundWelcomeInnerStart: '#29a9a524',
  backgroundWelcomeInnerEnd: '#e72feb24',
  backgroundBannerStart: '#ffd6c1',
  backgroundBannerEnd: '#e5d7ff',
  backgroundBannerBorderStart: '#f6ac66',
  backgroundBannerBorderEnd: '#d780ff',

  // Backgrounds: feature surfaces
  backgroundChatContinue: '#3d44561a',
  backgroundAiProvider: '#41475708',
  backgroundAiProviderHover: '#41475712',
  backgroundEmptyState: '#41475708',
  backgroundToolkitPanel: '#F4F5F5',
  backgroundIndexSuccess: '#2bd48d14',
  backgroundIndexError: '#d7161614',
  backgroundIndexWarning: '#e9791214',
  backgroundIndexInfo: '#29b8f514',

  // Backgrounds: folders
  backgroundFolder: '#ffffff99',
  backgroundFolderActive: '#6390fe1a',
  backgroundFolderBorderStart: '#00000000',
  backgroundFolderBorderEnd: '#00000000',
  backgroundFolderBorderHover: '#6390fe',
  backgroundFolderBorderActive: '#6390fe',
  backgroundFolderShadow: '#0000001f',
};
