export const lightEffectScheme = {
  mode: 'light',
  boxShadowDefault: '0px 2px 10px 0px',
  boxShadowTagEditorPaper: '0px 2px 10px 0px',
  boxShadowTag: '0px 2px 4px 0px',
  boxShadowOnboarding: '0rem 3.975rem 4.2625rem -3.8125rem',
  boxShadowAiAnswer: '0px 2px 7px 0px',
  backgroundCardGradientDirection: '180deg',
  backgroundCardHoverShadow: '0px -3px 0.9375rem 0px',
  backgroundTourCardDirection: '180deg',
  backgroundResourceBlueDirection: '0deg',
  backgroundResourceOrangeDirection: '180deg',
  backgroundResourcePurpleDirection: '180deg',
  backgroundResourceGreenDirection: '0deg',
  backgroundResourcePinkDirection: '180deg',
  backgroundAgentHubShadowDefault: null,
  backgroundAgentHubShadowHover: null,
  backgroundAgentHubShadowActive: '0px 0px 15px 0px',
  backgroundAgentHubTextGradientEnd: '30%',
  backgroundUserMessageActionsStop: '85.36%',
  backgroundAgentModalBorderDirection: '224.66deg',
  backgroundAgentModalBorderEnd: '99.46%',
  backgroundAgentModalDirection: '224.97deg',
  backgroundFolderBorderDirection: null,
  backgroundFolderShadow: '0 0.125rem 0.25rem',
  aiAssistantGradientDirection: '222.04deg',
  aiAssistantGradientStart: '10.38%',
  aiAssistantGradientEnd: '91.15%',
};
