export const darkEffectScheme = {
  mode: 'dark',
  boxShadowDefault: '0px 0px 8px 0px',
  boxShadowTagEditorPaper: '0px 8px 12px 0px',
  boxShadowTag: null,
  boxShadowOnboarding: '0rem 3.975rem 4.2625rem -3.8125rem',
  boxShadowAiAnswer: null,
  backgroundCardGradientDirection: '0deg',
  backgroundCardHoverShadow: '0px -3px 0.9375rem 0px',
  backgroundTourCardDirection: '360deg',
  backgroundResourceBlueDirection: '0deg',
  backgroundResourceOrangeDirection: '0deg',
  backgroundResourcePurpleDirection: '0deg',
  backgroundResourceGreenDirection: '0deg',
  backgroundResourcePinkDirection: '180deg',
  backgroundAgentHubShadowDefault: null,
  backgroundAgentHubShadowHover: null,
  backgroundAgentHubShadowActive: '0px 0px 12px 0px',
  backgroundAgentHubTextGradientEnd: '25%',
  backgroundUserMessageActionsStop: '82.5%',
  backgroundAgentModalBorderDirection: '224.97deg',
  backgroundAgentModalBorderEnd: '100%',
  backgroundAgentModalDirection: '199.39deg',
  backgroundFolderBorderDirection: '180deg',
  backgroundFolderShadow: '0 0 0',
  aiAssistantGradientDirection: 'to top right',
  aiAssistantGradientStart: '8.85%',
  aiAssistantGradientEnd: '89.62%',
};
