export const lightNodeColors = {
  toolkit: '#C0C4FF',
  mcp: '#F0A4FF',
  tool: '#E0E4FF',
  agent: '#D5FCD9',
  pipeline: '#EAD3FE',
  function: '#EFE3FB',
  llm: '#D2EDFF',
  decision: '#FFD2E6',
  condition: '#F8FCD5',
  loop: '#FFEDD4',
  loop_from_tool: '#FFE0D4',
  router: '#C7FFEF',
  state_modifier: '#E2FFBD',
  code: '#F5E6FF',
  printer: '#63EF9FFF',
  hitl: '#FFE0B6',
  custom: '#FFD5D5',
};
