// Maximum length for generated operationIds (tool names)
// Must match backend _MAX_OPERATION_ID_LENGTH constant
const MAX_OPERATION_ID_LENGTH = 64;

// Map HTTP methods to semantic action names for better readability
// Must match backend _METHOD_TO_ACTION mapping
const METHOD_TO_ACTION = {
  get: 'get',
  post: 'create',
  put: 'update',
  patch: 'update',
  delete: 'delete',
  head: 'head',
  options: 'options',
  trace: 'trace',
};

/**
 * Generate an operationId from HTTP method and path when not provided in spec.
 *
 * This function MUST produce identical output to the backend's _generate_operation_id()
 * to ensure UI preview matches actual tool names generated by the server.
 *
 * @param {string} method - HTTP method (GET, POST, etc.)
 * @param {string} path - URL path (e.g., /users/{id})
 * @returns {string} Generated operationId string
 *
 * @example
 * generateOperationId('GET', '/users') // => 'get_users'
 * generateOperationId('GET', '/users/{id}') // => 'get_users_by_id'
 * generateOperationId('POST', '/users') // => 'create_users'
 * generateOperationId('PUT', '/users/{id}') // => 'update_users_by_id'
 * generateOperationId('PATCH', '/users/{id}') // => 'update_users_by_id'
 * generateOperationId('DELETE', '/api/v1/items/{itemId}') // => 'delete_api_v1_items_by_itemId'
 */
export const generateOperationId = (method, path) => {
  // Map HTTP method to semantic action
  const methodLower = method.toLowerCase();
  const action = METHOD_TO_ACTION[methodLower] || methodLower;

  // Split path and process segments
  const segments = path.split('/').filter(s => s);
  const processedSegments = [];

  for (const segment of segments) {
    // Check if it's a path parameter like {id} or {userId}
    if (segment.startsWith('{') && segment.endsWith('}')) {
      const paramName = segment.slice(1, -1); // Remove braces
      processedSegments.push(`by_${paramName}`);
    } else {
      // Regular segment - replace any non-alphanumeric chars with underscore
      const cleanSegment = segment.replace(/[^a-zA-Z0-9]/g, '_');
      if (cleanSegment) {
        processedSegments.push(cleanSegment);
      }
    }
  }

  // Join: action_segment1_segment2_...
  const baseId = processedSegments.length > 0 ? `${action}_${processedSegments.join('_')}` : `${action}_root`; // Edge case: root path "/"

  // Ensure valid identifier (no leading digits)
  const prefixedId = /^\d/.test(baseId) ? '_' + baseId : baseId;

  // Truncate if too long, preferring word boundaries
  let finalId = prefixedId;
  if (prefixedId.length > MAX_OPERATION_ID_LENGTH) {
    let truncated = prefixedId.slice(0, MAX_OPERATION_ID_LENGTH);
    // Prefer truncating at a word boundary (underscore) if possible
    const lastUnderscore = truncated.lastIndexOf('_');
    if (lastUnderscore > 0) {
      truncated = truncated.slice(0, lastUnderscore);
    }
    // Ensure we don't end with an underscore after truncation
    finalId = truncated.replace(/_+$/, '');
  }

  return finalId;
};

export const openAPIExtract = openAPIJson => {
  if (openAPIJson) {
    const result = [];
    const paths = openAPIJson.paths || {};
    const pathNames = Object.keys(paths);

    for (const path of pathNames) {
      const pathItem = paths[path] || {};
      const methods = Object.keys(pathItem);

      for (const method of methods) {
        // Skip non-operation keys like 'parameters', 'summary', etc.
        if (
          !['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace'].includes(
            method.toLowerCase(),
          )
        ) {
          continue;
        }

        const operation = pathItem[method];
        // Use operationId if exists, otherwise generate from method+path
        const name = operation.operationId || generateOperationId(method, path);

        result.push({
          name,
          path,
          method,
          description: operation.description || operation.summary,
        });
      }
    }
    return result;
  }
  return [];
};
